# Generated by Django 3.1.5 on 2021-01-20 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1, 'Primer nombre no puede tener solo 1  caracter')])),
                ('segundo_nombre', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1, 'Segundo nombre no puede tener solo 1 caracter')])),
                ('apellido_paterno', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1, 'Apellido paterno no puede tener solo 1 caracter ')])),
                ('apellido_materno', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('rut', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
